### ISSUE TITLE
Sync and create

### ISSUE THREAD

**Issue by yoramdelangen** [Rekord/rekord-jquery#5]
How is the current flow for create/syncing with the REST Api currently? At the moment when I create a new record it does not sync directly, until I refresh the page or reinit the model it starting to sync/fetch latest changes. Is there a manual method for handling changes from both sides? For instance a 'sync' method?

**Comment by ClickerMonkey** [comment]
> At the moment when I create a new record it does not sync directly, until I refresh the page or reinit the model it starting to sync/fetch latest changes.

Can you show some code examples?

> Is there a manual method for handling changes

What do you mean by this example?

The idea is you create a model in one of two ways:

``` javascript
// first
var t0 = new Task();
t0.name = 'task #0';
t0.done = false;
t0.$save();

// second
var t1 = Task.create({
  name: 'task #1',
  done: false
});
```

After that - the part that keeps the model in "sync" across devices is adding a binding which implements the `Rest.live` interface like https://github.com/Rekord/rekord-pubsub, https://github.com/Rekord/rekord-firebase, and https://github.com/Rekord/rekord-pouchdb. 

You can manually call a sync with `t0.$refresh()` function which does a GET to the REST API passing the ID of the model in the URL.

Let me know what else I can clear up.

**Comment by ClickerMonkey** [comment]
Closing - assuming issuer figured out a solution.
