### ISSUE TITLE
Authentication layer

### ISSUE THREAD

**Issue by yoramdelangen** [Rekord/rekord-jquery#6]
Main API's are secured with Basic auth or JWT, are there any plans to support some basic security layers?

**Comment by ClickerMonkey** [comment]
At the moment the HTTP options passed to `$.ajax` are not extensible (where you would pass in user/pass for basic auth or other values for JWT). 

I plan on adding an object `Rekord.jQuery.Options` which allows you to specify options to always add to `$.ajax` as well as a function `Rekord.jQuery.adjustOptions` so you can dynamically customize the options object before its passed to `$.ajax`.

Expect this feature very soon!

**Comment by ClickerMonkey** [comment]
Released:

https://github.com/Rekord/rekord-jquery/releases/tag/1.1.3

**Comment by yoramdelangen** [comment]
Sweet!! I'm going to check it out! Thnx
